import type { Stage } from './types'

export const STAGES: Stage[] = [
  {
    id: 's1', num: 1,
    name: 'MASTERING\nMUSIC',
    eyebrow: 'Foundations',
    colour: '#e8c547',
    cardClass: 's1-card',
    tagline: 'Know the music. Know when everything happens.',
    desc: 'Before you can coach, you need to hear. Stage 1 is about building your relationship with the music — understanding song structure, the RIDE choreography roadmap, and how to use what you hear to anticipate what comes next.',
    ref: 'Manual §2 — The Architect (p.17–25)',
    days: [
      { title: 'The RIDE Framework', focus: 'Foundation',
        manualNote: 'Music is the framework for the workout. Each song is chosen for its unique offer — not as background, but as the training architecture itself. §2 Overview (p.17)',
        tasks: [
          { text: 'Read §2 Architect overview (p.17–18). In one sentence: why does RIDE use music as the framework rather than time?', ref: 'Manual p.17' },
          { text: 'Study the full RIDE Class Profile — all 8 tracks, training outcomes, positions, cadence ranges, target zones. Know this table.', ref: 'Manual p.19 Fig 2.1' },
          { text: 'Ride a full RIDE class as a participant only. No coaching thoughts. Just feel what each track asks of your body.', ref: 'Practical' },
          { text: 'After the ride: write one word for each track — what the music made you feel. This is your coaching starting point.', ref: 'Reflection' },
        ] },
      { title: 'Song Structure — The Map', focus: 'Theory',
        manualNote: 'Verse, Chorus, Bridge, Instrumental Break. Understanding each element lets you formulate work:rest components within each track. §2.3 (p.22)',
        tasks: [
          { text: 'Read §2.3 Understanding Song Structure (p.22). Define Verse, Chorus, Bridge and Instrumental Break in your own words — without looking back at the page.', ref: 'Manual p.22' },
          { text: 'Listen to one RIDE track. Identify and write every song section in the order it happens. Include timestamps.', ref: 'Practical' },
          { text: 'Listen again. Mark where energy rises, drops, builds and releases. Where does the music create training opportunities?', ref: 'Ear Training' },
          { text: "Teach the structure to someone who hasn't ridden RIDE. Can you explain why the song's architecture matters for the room?", ref: 'Teach It' },
        ] },
      { title: 'Reading the Choreography Sheet', focus: 'Reading',
        manualNote: 'The choreography sheet has 9 identifiers. Identifier 6 is the musical roadmap — the single most important tool for pre-cueing. §2.2 (p.20–21)',
        tasks: [
          { text: 'Study §2.2 — the 9 choreography identifiers (p.20–21). Cover the page. Write out what each identifier number means without looking.', ref: 'Manual p.21' },
          { text: 'Open a RIDE choreography sheet. Locate all 9 identifiers. Find: song title, burn-o-meter, musical roadmap, effort blocks, cadence prescription.', ref: 'Chore Sheet' },
          { text: 'Follow the musical roadmap (identifier 6) while listening to the track. Can you predict the changes before they happen?', ref: 'Practical' },
          { text: "Read one chore sheet and write a 3-line plain English overview of the track — as if you're briefing a colleague who's never seen it.", ref: 'Synthesis' },
        ] },
      { title: 'Hearing the Music — Active Listening', focus: 'Ear Training',
        manualNote: 'Pre-cueing requires knowing the flow of music — when and where to give instructions to align with the energy and mood. §4.3 (p.44)',
        tasks: [
          { text: 'Choose one track. Listen without the chore sheet. Count the 8-count phrases. Where do choruses start? Where does the energy shift?', ref: 'Practical' },
          { text: 'Listen again with the chore sheet. Match every PC (pre-cue) marker to what you hear. Do the markers fall where you expected?', ref: 'Chore Sheet + Track' },
          { text: 'Listen a third time. Identify 3 moments where a pre-cue would land with maximum impact. Write them down with the timestamp.', ref: 'Reflection' },
          { text: 'On the bike: ride the track and call out section names aloud as they change — no coaching, just naming. How many did you hit on time?', ref: 'Bike Practice' },
        ] },
      { title: 'Track 1 — Warm Up Deep Dive', focus: 'Track Study',
        manualNote: 'Track 1 Warm-Up: Zones 1–2, 80–100 rpm, Seated Easy Racing. The room enters here. How you open the space sets everything that follows. §2.1',
        tasks: [
          { text: 'Read the Track 1 choreography fully. Map every section: Set-Up, efforts, bridge moments, outro. Know the shape of the track.', ref: 'Chore Sheet T1' },
          { text: 'Ride Track 1 and call out each section change aloud as it happens — naming only, no coaching. Hit every change on the music.', ref: 'Practical' },
          { text: "Write a track intro for Track 1 — the 2–3 sentences you'd say to the room before the music starts. Include the training objective.", ref: 'Scripting Task' },
          { text: 'Without the sheet: from memory, write the Track 1 structure section by section. Check. Mark what you missed.', ref: 'Memory Test' },
        ] },
      { title: 'Tracks 2 & 3 — Structure Mapping', focus: 'Track Study',
        manualNote: 'Track 2 Mixed Pace: 60–120rpm varied cadence, Zones 2–3. Track 3 Climbing: Seated + Standing Climb, 60–70rpm, Zones 3–4. §2.1',
        tasks: [
          { text: "Study chore sheets for Tracks 2 and 3. Write a one-line training objective for each track in rider-facing language — what are they actually doing?", ref: 'Chore Sheets T2, T3' },
          { text: 'Listen to both tracks back to back without the sheet. Mark every energy shift you hear. How many match the chore markers?', ref: 'Ear Training' },
          { text: 'Ride Track 3. For each effort block — seated climb, standing climb — feel the difference. Write: what does the body ask for in each?', ref: 'Practical' },
          { text: 'Identify the single hardest pre-cue moment across both tracks. Why is it hard? What do you need to know to nail it?', ref: 'Reflection' },
        ] },
      { title: 'Tracks 4–6 — High Intensity Music', focus: 'Track Study',
        manualNote: 'Track 4 Attack: Standing Attack, 80–90rpm, Zones 4–5. Track 5 Race: 90–140rpm, Zones 2–3. Track 6 Power Intervals: Above Threshold, 90–110rpm. §2.1',
        tasks: [
          { text: 'Study chore sheets for Tracks 4, 5 and 6. Note how the music dynamics match the higher training zones. What changes in the energy?', ref: 'Chore Sheets T4–T6' },
          { text: 'Listen to Track 4 (Attack Intervals). Can you hear the music driving the explosive efforts? Describe in 2 sentences what you hear.', ref: 'Practical' },
          { text: 'Ride Track 6 (Power Intervals). Stay locked to the chore. Feel the work:rest structure. Is the music telling you when to go and when to recover?', ref: 'Bike Practice' },
          { text: 'Compare the musical energy of Track 3 (climb) vs Track 6 (power). What is different, and why does that matter for how you coach each?', ref: 'Reflection' },
        ] },
      { title: 'Tracks 7 & 8 — Peak to Recovery', focus: 'Track Study',
        manualNote: 'Track 7 Peak: Lactate Threshold+, Zones 5+. Track 8 Ride Home: Recovery, Flush & Mobility. The arc from peak effort to stillness. §2.1',
        tasks: [
          { text: 'Study chore sheets for Tracks 7 and 8. How does the musical arc across these two tracks mirror the physical journey from peak to recovery?', ref: 'Chore Sheets T7, T8' },
          { text: 'Listen to Track 8 (Ride Home). Write: how does this music feel different to Track 7? What does that difference ask of the instructor?', ref: 'Reflection' },
          { text: 'Write a 3-sentence summary of the full RIDE class musical journey — Track 1 through Track 8. One sentence per three tracks.', ref: 'Synthesis' },
          { text: 'Ride the final two tracks back to back. Consciously match your energy to the music. What happens in your body when you follow the music rather than lead it?', ref: 'Bike Practice' },
        ] },
      { title: 'Song Dynamics — The Analysis Task', focus: 'Assessment Prep',
        manualNote: "Section + Song Dynamics (what's going on) + Interpretation/Energy (how can I express it). Manual Assessment Task (p.25)",
        tasks: [
          { text: 'Complete the Track 2 Analysis table from the manual (p.25): for each section write the Song Dynamics and Interpretation/Energy.', ref: 'Manual p.25' },
          { text: 'Record yourself riding and talking through one full track — naming each section as it changes. Listen back. Did you catch every change?', ref: 'Video Task — upload link below' },
          { text: 'Self-assess on all 8 tracks: can you identify every section by ear? Rate yourself 1 (not confident) to 5 (instinctive) per track.', ref: 'Self Assessment' },
          { text: 'Find one track where you rated yourself below 3. Listen to it 3 times today — map, study, ride. Come back and re-rate.', ref: 'Target Practice' },
        ] },
      { title: 'Stage 1 Competency Check', focus: 'Sign Off',
        manualNote: '75% task completion + coach sign-off = Stage 1 complete. You are ready for Stage 2 — Magic in Movement.',
        tasks: [
          { text: 'Full class ride: without looking at chore sheets, internally map every section change across all 8 tracks. Debrief with coach immediately after.', ref: 'Practical Assessment' },
          { text: 'Verbal walkthrough with coach: explain the structure of any 2 tracks chosen by coach on the spot.', ref: 'Coach Assessment' },
          { text: 'Submit your Track 2 analysis table and self-assessment ratings to coach.', ref: 'Written Submission' },
          { text: "Honest reflection: which part of the music still surprises you? Write it down. That's your Stage 2 starting point.", ref: 'Self Knowledge' },
        ] },
    ],
  },
  {
    id: 's2', num: 2,
    name: 'MAGIC IN\nMOVEMENT',
    eyebrow: 'Advanced',
    colour: '#4ecdc4',
    cardClass: 's2-card',
    tagline: 'Confident choreography. Physiology applied to the ride.',
    desc: "Stage 2 is where music meets body. You'll lock in choreography for all eight tracks, understand how each position and movement connects to what's actually happening physiologically, and build the physical confidence to demonstrate, lead and instruct with precision.",
    ref: 'Manual §3 The Athlete (p.26–40) + §2 Architect',
    days: [
      { title: 'Bike Setup — The Foundation of Safety', focus: 'Safety + Physiology',
        manualNote: 'Incorrect saddle height, fore-aft position and handlebar height cause injury. Every person who gets on a RIDE bike is your responsibility. §3.3–3.4 (p.29–30)',
        tasks: [
          { text: 'Read §3.3 Bike Set-Up (p.29) and §3.4 Common Set-Up Faults (p.30). Memorise the 3 most common faults and their physical consequences.', ref: 'Manual p.29–30' },
          { text: "Set up a bike from scratch using the manual guidelines. Then deliberately introduce each common fault and physically feel the difference.", ref: 'Practical' },
          { text: 'Practise setting up a bike correctly in under 60 seconds. This is the standard. Time yourself.', ref: 'Speed Drill' },
          { text: 'Set up a bike for another person using only their standing height as your starting point. Talk through every adjustment aloud as you make it.', ref: 'Teach It' },
        ] },
      { title: 'Riding Positions — Seated', focus: 'Technique',
        manualNote: 'Seated Easy Racing and Seated Climb are the foundation of RIDE. Each has distinct Points of Performance. §3.5 (p.31+)',
        tasks: [
          { text: 'Read §3.5 Riding Positions. Study the Points of Performance for Seated Easy Racing and Seated Climb — what is different about each?', ref: 'Manual p.31+' },
          { text: 'Ride both seated positions for 5 minutes each. Focus on spine, hip position, foot pressure, breathing, and cadence quality.', ref: 'Practical' },
          { text: "Write 2 coaching cues for each seated position — one for what the body should feel, one for what good looks like from the outside.", ref: 'Coaching Task' },
          { text: "Observe another person riding. Can you identify whether they're in a true Seated Climb or just a slower Seated Easy? What tells you?", ref: 'Observation' },
        ] },
      { title: 'Riding Positions — Standing', focus: 'Technique',
        manualNote: 'Standing Climb, Standing Attack, Time Trial — each has distinct biomechanical demands. The transition between positions is as important as the position itself. §3.5',
        tasks: [
          { text: 'Study Standing Climb, Standing Attack, and Time Trial from §3.5. Write the key Points of Performance differences between all three.', ref: 'Manual §3.5' },
          { text: 'Ride all three standing positions. Pay attention to weight distribution, grip, core engagement, and where power is generated differently in each.', ref: 'Practical' },
          { text: 'Practise the transition from Seated Climb to Standing Climb 10 times — smooth, on an imagined beat.', ref: 'Transition Drill' },
          { text: 'Write coaching cues for attack gear: heavy gear you can stand and run with, still keep pace.', ref: 'Coaching Task' },
        ] },
      { title: 'Biomechanics — The Pedal Stroke', focus: 'Physiology',
        manualNote: 'Pedalstroke: Upstroke + Downstroke (Push + Pull). Most riders use 50% of the available power. §3.2 (p.28)',
        tasks: [
          { text: 'Read §3.2 Biomechanics of Cycling (p.28). Understand both phases of the pedal stroke and the primary muscle groups involved in each.', ref: 'Manual p.28' },
          { text: 'Ride a 5-minute seated climb. Focus entirely on the upstroke — consciously pulling through the bottom of the stroke.', ref: 'Practical' },
          { text: "Write a 2-sentence coaching cue that helps riders feel the pull phase — without using anatomical language.", ref: 'Coaching Task' },
          { text: 'Now write a cue for the full pedal stroke that a beginner and an experienced rider can both apply at the same time.', ref: 'Differentiated Coaching' },
        ] },
      { title: 'Training Zones — Applied to RIDE', focus: 'Physiology',
        manualNote: '7 training zones mapped to FTP, HR% and RPE. RIDE uses Zones 1–5+ across 8 tracks. §1.6 (p.15–16)',
        tasks: [
          { text: 'Study the Training Zone table §1.6 (p.15). For each RIDE track, identify the target zones from the Class Profile (p.19). Know every pairing.', ref: 'Manual p.15 + p.19' },
          { text: 'Ride Tracks 3 and 6. Call out the zone number aloud for each effort block as you ride it.', ref: 'Practical' },
          { text: 'Write one rider-facing intensity cue per zone (Zones 1–5). No zone numbers. Describe what the body feels.', ref: 'Coaching Task' },
          { text: "Which zone is hardest to coach? Write 3 different cues for that zone — one for beginners, one for intermediates, one for experienced riders.", ref: 'Differentiated Coaching' },
        ] },
      { title: 'Choreography Lock-In — Tracks 1–3', focus: 'Chore Lock-In',
        manualNote: 'Pre-choreography exists so you can focus on coaching — not remembering. When chore is locked, your mind is free to read the room. §2.1 (p.18)',
        tasks: [
          { text: 'Script Tracks 1, 2, and 3: write every position change with the music cue that triggers it and the pre-cue timing.', ref: 'Chore Sheets T1–T3' },
          { text: 'Ride Tracks 1–3 continuously. Execute every position change at the correct musical moment. No coaching — just movement precision.', ref: 'Practical' },
          { text: 'Ride again — add one verbal pre-cue per major position change. One sentence. Delivered on the beat.', ref: 'Voice + Movement' },
          { text: 'Ride a third time with someone watching. Ask them: did every transition happen with the music? Where was the gap?', ref: 'Observed Practice' },
        ] },
      { title: 'Choreography Lock-In — Tracks 4–6', focus: 'Chore Lock-In',
        manualNote: 'Attack and Power tracks require fast position changes at high cadence. At 90+ rpm, being half a beat late costs the room.',
        tasks: [
          { text: 'Script Tracks 4, 5 and 6. Identify every transition that feels hardest — where do you need to pre-cue earliest?', ref: 'Chore Sheets T4–T6' },
          { text: 'Ride Track 4 (Attack). Every standing movement must hit the music marker exactly. Count your hits and misses.', ref: 'Practical — Video Task' },
          { text: 'Drill the 2 hardest transitions from Tracks 4–6 in isolation. 10 repetitions each, slow first then full speed.', ref: 'Drill Task' },
          { text: 'Record yourself riding Track 5. Watch it back. How many transitions landed on the music?', ref: 'Video Analysis' },
        ] },
      { title: 'Choreography Lock-In — Tracks 7 & 8', focus: 'Chore Lock-In',
        manualNote: 'Track 7 is the physical peak. Track 8 is the descent. Your body language and movement must match the music.',
        tasks: [
          { text: 'Script Tracks 7 and 8 fully. For Track 8 especially: how does your body language and movement need to change to match the recovery energy?', ref: 'Chore Sheets T7, T8' },
          { text: 'Ride the full release (Tracks 1–8) with focus solely on choreography precision. No coaching at all. Every transition on the beat.', ref: 'Full Class Practical' },
          { text: 'After the full ride: write 3 transitions that need more work. What specifically slipped?', ref: 'Reflection' },
          { text: 'Ride the full release again tomorrow. Same focus. Compare your notes.', ref: 'Repeat Practice' },
        ] },
      { title: 'Physical Confidence — Demonstrating', focus: 'Performance',
        manualNote: 'Previewing is a visual pre-cue — lead the movement before the class, let them see and follow. §4.4 (p.44)',
        tasks: [
          { text: 'Read §4.4 Previewing & Doing (p.44). Understand how showing a movement acts as a visual pre-cue for the room.', ref: 'Manual p.44' },
          { text: 'Practise the Seated to Standing Climb transition as a preview — last 2 counts of one phrase, begin the movement, let the class follow. Repeat 10 times.', ref: 'Practical' },
          { text: 'Team teach Tracks 2 and 3 with a coach or colleague. Focus only on: correct position on the beat, clean previewed transitions.', ref: 'Team Teach' },
          { text: "Ask your teaching partner: did they feel led or pulled? What did they follow — your voice, your body, or the music?", ref: 'Debrief' },
        ] },
      { title: 'Stage 2 Competency Check', focus: 'Sign Off',
        manualNote: '75% task completion + coach sign-off = Stage 2 complete. You are ready for Stage 3 — Finding Your Voice.',
        tasks: [
          { text: 'Teach Tracks 3, 4 and 5 to coach with full choreography precision. Every position change on the correct musical cue.', ref: 'Practical Assessment' },
          { text: "Bike setup assessment: correctly set up a bike for a rider from coach's specifications. Under 60 seconds.", ref: 'Coach Assessment' },
          { text: 'Written: for any 3 tracks chosen by coach, write the training zone, the positions used, and one intensity coaching cue per effort block.', ref: 'Written Submission' },
          { text: "Personal reflection: when does your body feel most alive on the bike? That answer tells you which track will become your signature.", ref: 'Self Knowledge' },
        ] },
    ],
  },
  {
    id: 's3', num: 3,
    name: 'FINDING\nYOUR VOICE',
    eyebrow: 'Mastery',
    colour: '#ff6b9d',
    cardClass: 's3-card',
    tagline: 'Find your coaching style. Hold the room.',
    desc: "Stage 3 is where technical knowledge becomes coaching. You'll develop the DCDR coaching loop, build your own cueing library, and find the voice, tone and language that is uniquely yours.",
    ref: 'Manual §4 The Coach (p.41–51)',
    days: [
      { title: 'The DCDR Coaching Loop', focus: 'Framework',
        manualNote: 'Describe it → Cue it → Do it → Review it. Four moments around every training phase. §4.2 (p.43)',
        tasks: [
          { text: 'Read §4.2 Coaching Communication Loop (p.43). Draw the DCDR loop from memory — label what happens at each stage.', ref: 'Manual p.43' },
          { text: 'Listen to a full RIDE class. For one track, identify every moment where you hear Describe, Cue, Do and Review.', ref: 'Listening Task' },
          { text: "Write a DCDR script for Track 3, Block 1. One sentence per phase. Keep it tight — if you can't say it in one sentence, it's not a cue yet.", ref: 'Scripting Task' },
          { text: 'Teach Track 3 Block 1 to a person or the mirror using your DCDR script. Then teach it again without the script. What changed?', ref: 'Teach It' },
        ] },
      { title: 'Track Objectives — Purpose Before Effort', focus: 'Coaching Foundation',
        manualNote: 'Objectives give riders a reason to push. Without a why, effort is just suffering. §4.1 (p.42)',
        tasks: [
          { text: 'Read §4.1 Track & Training Objectives (p.42). Write one training objective for each of the 8 RIDE tracks. One sentence each. Rider-facing language.', ref: 'Manual p.42' },
          { text: 'For Track 6 (Power Intervals): write a block objective for every effort segment.', ref: 'Coaching Task' },
          { text: 'Ride Track 4 and deliver your scripted objectives aloud. Record if possible. Listen back: does each objective land clearly?', ref: 'Practical — Video Task' },
          { text: "Which objective felt most powerful when you said it? Why? That's the language that already sounds like you.", ref: 'Voice Discovery' },
        ] },
      { title: 'Cueing — Position & Pressure', focus: 'PPP: Position + Pressure',
        manualNote: 'Cue it = Position, Pressure, Pace, Technique, Timing. Each cue is instructions at a specific moment. §4.3 (p.44)',
        tasks: [
          { text: 'Read §4.3 Cueing & Pre-Cueing (p.44). Understand the difference between a cue (at the moment) and a pre-cue (before the moment).', ref: 'Manual p.44' },
          { text: 'Write 3 position coaching cues for Standing Climb. Each must tell the rider what their body should feel.', ref: 'Coaching Task' },
          { text: 'Write 3 pressure coaching cues for a Seated Climb effort. Describe the physical sensation.', ref: 'Coaching Task' },
          { text: 'Record yourself coaching the first effort block of Track 3. Listen back: are you cueing or narrating?', ref: 'Video Analysis' },
        ] },
      { title: 'Cueing — Pace & Timing', focus: 'PPP: Pace + Timing',
        manualNote: "Pre-cueing is giving the instruction BEFORE the change — last 2 or 4 counts of the phrase. If the class is still responding when the change happens, you were too late.",
        tasks: [
          { text: 'Write 3 pace coaching cues for Track 5 (Race Endurance). Describe cadence change in terms of how it feels.', ref: 'Coaching Task' },
          { text: 'Practise pre-cueing with exactly 2 counts to spare before a position change. Repeat until the timing is instinctive.', ref: 'Practical Drill' },
          { text: 'Record yourself coaching Tracks 2 and 3. Listen back: do your pre-cues land with enough time?', ref: 'Video Task — upload link below' },
          { text: 'Teach Track 2 with a rule: no cue after the change has happened. Only pre-cues. What does that discipline do to your coaching?', ref: 'Constrained Practice' },
        ] },
      { title: 'Removing the Fluff', focus: 'Economy of Language',
        manualNote: "Every word that doesn't serve the rider is a word that reduces your impact.",
        tasks: [
          { text: "Take your scripted Track 3 coaching. Underline every word that directly serves the rider. Cross out everything else. Read what's left.", ref: 'Editing Task' },
          { text: 'Ride Track 6 with a rule: 8 words maximum per cue. No exceptions. Record and listen back.', ref: 'Practical — 8-Word Rule' },
          { text: 'What is the one coaching phrase you rely on most? Write 3 alternatives that express the same intent — differently.', ref: 'Variety Task' },
          { text: "Teach Track 4 to a partner. Ask them to raise a hand every time a cue lands clearly. Look away for filler. What's the ratio?", ref: 'Partner Feedback' },
        ] },
      { title: 'Voice — Tone, Volume & Energy', focus: 'Vocal Delivery',
        manualNote: 'Volume, speech speed, tone aligned to music, sentence length — four tools. §4.5 (p.47)',
        tasks: [
          { text: 'Read §4.5 Developing Your Own Style (p.47). The four vocal variation tools: volume, speed, tone, sentence length. Write one specific application for each.', ref: 'Manual p.47' },
          { text: 'Coach Track 4 with deliberate vocal intensity — quiet build into the effort, loud drive at the peak, soft review after. Record it.', ref: 'Practical — Video Task' },
          { text: "Listen back to your recording. Did your voice match the music's energy? Mark the moments where it aligned.", ref: 'Self Analysis' },
          { text: 'Coach the same track again — but this time, listen to the music with your eyes closed for 30 seconds first. Let the energy enter you before you speak.', ref: 'Embodiment Practice' },
        ] },
      { title: 'Block Focus & Motivation', focus: 'Motivational Coaching',
        manualNote: "Every effort block has a focus. Motivation that doesn't connect to that focus is noise.",
        tasks: [
          { text: 'For Tracks 6 and 7, write a motivational cue for every effort block. Not generic — specific to what that block is physically demanding.', ref: 'Coaching Task' },
          { text: 'Ride Track 7 and deliver your motivational cues aloud. After, reflect: which ones felt genuine?', ref: 'Practical + Reflection' },
          { text: "Write 3 phrases that feel authentically yours — language you'd actually use, that reflects who you are as a coach.", ref: 'Voice Development' },
          { text: "Ask someone who knows you well to describe how you motivate people in everyday life. Write down what they say. That's the raw material.", ref: 'Identity Research' },
        ] },
      { title: 'Building Your Coaching Library', focus: 'Library Building',
        manualNote: 'Variety in cues builds rider engagement. Aim for at least 3 options per coaching category so the room always hears something new.',
        tasks: [
          { text: 'Build your cue library: write 3 cues each for Position (x4 positions = 12), Pressure (x3), Pace (x3), Intensity (x3). Minimum 21 cues.', ref: 'Personal Library' },
          { text: 'Read your full library aloud. Which ones sound like you? Which ones sound like someone else? Mark them honestly.', ref: 'Voice Audit' },
          { text: "Practise delivering each cue at different moments in a track — not just the obvious ones. Which cues work anywhere?", ref: 'Practical' },
          { text: 'Remove 5 cues from your library — the ones that feel weakest. Replace them with 5 new ones.', ref: 'Library Edit' },
        ] },
      { title: 'Full Class — Find Your Style', focus: 'Integration',
        manualNote: 'A great RIDE leader adapts their coaching style to the personality of the track. §4.5.',
        tasks: [
          { text: 'Coach a full RIDE class (all 8 tracks) with a coach or small group observing. Apply DCDR, block objectives, pre-cueing and vocal variation.', ref: 'Full Class Teach' },
          { text: "After the class: write 3 moments that felt like your natural coaching voice. 3 moments that still felt rehearsed.", ref: 'Reflection' },
          { text: "Ask one rider after class: what did they notice? Not what was good or bad — just what they noticed. Write it down.", ref: 'Member Feedback' },
          { text: "Read your reflection and the member feedback together. Is the same thing showing up? That intersection is who you are as a coach right now.", ref: 'Synthesis' },
        ] },
      { title: 'Stage 3 Competency — License to RIDE', focus: 'Sign Off',
        manualNote: '75% task completion + coach sign-off = RIDE Certified.',
        tasks: [
          { text: "Teach 3 tracks of coach's choice. Must demonstrate: DCDR structure, block objectives, accurate pre-cueing, and vocal variation.", ref: 'Practical Assessment' },
          { text: 'Verbal: explain the 4 elements of the DCDR coaching loop and give a live example from a track you\'ve just taught.', ref: 'Verbal Assessment' },
          { text: 'Submit your coaching library (minimum 21 cues) and your full Stage 3 reflection notes to coach.', ref: 'Portfolio Submission' },
          { text: 'Write one sentence about the kind of RIDE instructor you intend to be. Not what you want to do — who you intend to be.', ref: 'Intention Statement' },
        ] },
    ],
  },
]

export const TOTAL_TASKS = STAGES.reduce((acc, s) => acc + s.days.reduce((a, d) => a + d.tasks.length, 0), 0)

export const STAGE_LINES = [
  "You're building your ear right now. Every listen is training.",
  "You're finding the music in your body. Trust the work.",
  "You're finding your voice. This is where it gets real.",
  "You've done the work. Your coach is ready to hear from you.",
]
